utils::globalVariables(c(
  ".",
  "Average Price",
  "County",
  "First Date",
  "Latest Date",
  "Market",
  "N",
  "Records",
  "Year",
  "avg_price",
  "category",
  "change",
  "commodity",
  "county",
  "ke_food_prices",
  "latitude",
  "longitude",
  "market",
  "mean_price",
  "observations",
  "pct_change",
  "pricetype",
  "year_month_date",
  "year_quarter_date"
))
