name: R Data Update and package compilation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'  # Adjust as necessary for your timing needs

permissions:
  contents: write

jobs:
  Download data, Compile,Commit:
    runs-on: ubuntu-22.04
    env:
      TZ: "Africa/Nairobi"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install system dependencies for tidyverse and devtools
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev libicu-dev libblas-dev liblapack-dev zlib1g-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'  # Adjust as necessary

    - name: Install R packages including devtools
      env:
        GITHUB_PAT: ${{secrets.GH_PAT }}
      run: |
        Rscript -e "install.packages(c('lubridate','ggplot2','dplyr', 'data.table', 'remotes', 'rmarkdown', 'usethis', 'devtools'), repos = 'http://cran.rstudio.com')"


    - name: Run R script
      run: |
        Rscript data-raw/my_dataset.R
        Rscript -e "rmarkdown::render('README.Rmd', output_format = 'github_document')"

    - name: Build and Check the package
      run: |
        Rscript -e "devtools::build()"
        Rscript -e "devtools::check()"

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config pull.rebase false
        git pull origin main
        date=$(date +'%Y-%m-%d')
        git add .
        git commit -m "automatic updates $date" || echo "Nothing to update"

    - name: Push updated data
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GH_PAT}}
          branch: main
